### ISSUE TITLE
Request: Code splitting

### ISSUE THREAD

**Issue by Twipped** [doteric/funpack#10]
My function file has a collection of dynamically imported pathways that I only load on request, to reduce cold start time.

```js
const ROUTES = {
  route1: () => import('./routes/route1.js'),
  route2: () => import('./routes/route2.js')
};
```

I tried to enable esbuild's code splitting function through config overrides, like so:

```json
  "funpack": {
    "settings": {
      "outputDir": "./dist",
      "esbuildConfigOverride": {
        "format": "esm",
        "target": "node16",
        "sourcemap": true,
        "splitting": true,
        "outdir": "./dist",
        "outfile": ""
      }
    },
    "functions": {
      "activitypub": "./endpoints.js"
    }
  }
```

Note, I had to pass an empty string to outfile, because you can't use both outdir and outfile at the same time.

The problem is, when generatePackageJson hits this blank outfile, it throws up an error, because it doesn't know where to write the main file. Esbuild is generating an `endpoints.js` file in the dist folder, so I'm thinking this an configuration concern? I'm not sure how to address it.

**Comment by doteric** [comment]
Hey @Twipped ,
I've tried splitting before, but I can't recall how did it exactly go. I'm back home so I'll check this today ASAP and give you some solution.
Thanks for reporting this btw 💪

**Comment by doteric** [comment]
@Twipped 
Whenever you have some time:

Please check the following PR: https://github.com/doteric/funpack/pull/11
And check if this beta version works as expected for you: https://www.npmjs.com/package/funpack/v/1.1.0-beta-1

Please also adjust your config to the following:
```json
funpack: {
      settings: {
        outputDir: 'dist',
        //cleanupOutputDir: true, // Recommended to cleanup old files
        //zip: true,
        esbuildConfigOverride: {
          format: 'esm',
          target: 'node16',
          splitting: true,
          sourcemap: true,
        },
      },
      functions: {
        "activitypub": "./endpoints.js"
      },
```

**Comment by Twipped** [comment]
Config:

```json
"funpack": {
    "settings": {
      "outputDir": "./dist",
      "esbuildConfigOverride": {
        "format": "esm",
        "target": "node16",
        "sourcemap": true,
        "splitting": true
      }
    },
    "functions": {
      "activitypub": "./entrypoints.js"
    }
  },
```

I get the following:

```
> funpack

✘ [ERROR] Must use "outdir" when code splitting is enabled

/Users/twipped/Projects/lambdastodon/node_modules/esbuild/lib/main.js:1624
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
error: Must use "outdir" when code splitting is enabled
    at failureErrorWithLog (/Users/twipped/Projects/lambdastodon/node_modules/esbuild/lib/main.js:1624:15)
    at /Users/twipped/Projects/lambdastodon/node_modules/esbuild/lib/main.js:1266:28
    at runOnEndCallbacks (/Users/twipped/Projects/lambdastodon/node_modules/esbuild/lib/main.js:1179:65)
    at buildResponseToResult (/Users/twipped/Projects/lambdastodon/node_modules/esbuild/lib/main.js:1264:7)
    at /Users/twipped/Projects/lambdastodon/node_modules/esbuild/lib/main.js:1377:14
    at /Users/twipped/Projects/lambdastodon/node_modules/esbuild/lib/main.js:678:9
    at handleIncomingPacket (/Users/twipped/Projects/lambdastodon/node_modules/esbuild/lib/main.js:775:9)
    at Socket.readFromStdout (/Users/twipped/Projects/lambdastodon/node_modules/esbuild/lib/main.js:644:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Must use "outdir" when code splitting is enabled'
    }
  ],
  warnings: []
}
```

**Comment by doteric** [comment]
@Twipped 
Hmm, does this work correctly? 🤔 
```
"funpack": "doteric/funpack#feat/splitting",
```

Try `npm install --save-dev funpack@beta`, which will install the following version:
https://www.npmjs.com/package/funpack/v/1.1.0-beta-1

**Comment by Twipped** [comment]
Completely new problem!

```
> funpack

/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:17
    const importedPackages = new Set();
                             ^

RangeError: Maximum call stack size exceeded
    at new Set (<anonymous>)
    at getImportedPackages (/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:17:30)
    at getImportedPackages (/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:24:30)
    at getImportedPackages (/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:24:30)
    at getImportedPackages (/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:24:30)
    at getImportedPackages (/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:24:30)
    at getImportedPackages (/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:24:30)
    at getImportedPackages (/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:24:30)
    at getImportedPackages (/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:24:30)
    at getImportedPackages (/Users/twipped/Projects/lambdastodon/activitypub/node_modules/funpack/dist/utils/getImportedPackages.js:24:30)
```

> Hmm, does this work correctly? 🤔

Yup, that's the pattern that tells npm to fetch from a github branch.

**Comment by Twipped** [comment]
While I'm here, I also notice it doesn't copy over the `"type": "module` value on the package.json

**Comment by Twipped** [comment]
It also doesn't honor mjs files. The output result is always `.js`

**Comment by doteric** [comment]
@Twipped 
To use esmodules simply put in `"type": "module"` inside the main `package.json` and in the `funpack` config add:
```json
{
  ...
  "funpack": {
    "settings": {
      ...
      "packageFieldsToCopy": [
        "type"
      ],
      ...
    },
    ...
  }
}
```

**Comment by doteric** [comment]
Can you also throw me how your root `package.json` looks like fully? As well as change the `"edge": "./index.mjs"` to `"edge": "./index.js"` for now until the `mjs` extension support is added please? :D I will hopefully add the `.mjs` file extension support today, but you can still just use `"type": "module"` and it should work fine :D

**Comment by Twipped** [comment]
I've added you to the repo so you can see the structure. This is a separate lambda from the first one I was trying to split.
I disabled cleanupOutputDir because it was deleting everything in `dist`, including my other lambdas. This is a monorepo, I have the different lambdas grouped as separate projects.

**Comment by Twipped** [comment]
The callstack error isn't related to splitting, apparently. I get it on the `activitypub` lambda even when its disabled.

**Comment by doteric** [comment]
Yeah, the `callstack` is nothing related definitely.
So here is what I can recommend to you:
Create one directory something like `lambdas` and inside there place a `package.json` and also create a directory called `src` where you'd create a directory per function/lambda (no package.json there though). Declare all the functions inside `functions` of the `funpack` config and it will package everything for you and create a `package.json` with the actual dependencies list that are used.  
Example setup screenshot:
![image](https://user-images.githubusercontent.com/33552134/201981372-8fb58094-5d32-4e0b-a27d-9c9ee4af4aeb.png)

And a config like so:
```json
{
  ...
  "type": "module",
  "funpack": {
    "settings": {
      "esbuildConfigOverride": {
        "format": "esm",
        "target": "node16"
      },
      "packageFieldsToCopy": [
        "type"
      ],
      "zip": true
    },
    "functions": {
      "my-lambda1": "./src/my-lambda1/index.ts",
      "second_lambda": "./src/second_lambda/index.ts"
    }
  },
  ...
}
```

**Comment by Twipped** [comment]
I'd really rather not move all my lambdas under a single package.json, they all have different purposes and testing needs. Is the issue that the lib doesn't know how to handle npm-workspaces?

**Comment by doteric** [comment]
It should support it fine, I don't think there will be any problems, so of course you can use that also indeed :D  
The thing is that you could also do the approach I mentioned and have a single configuration for every lambda and just differ them by the source code of them. Each function will only use the dependencies that it actually needs nothing more :D  

And I've found the problem... I've put a wrong example here in this issue. `packageFieldsToCopy` should be under `settings` so like so:
```json
    "settings": {
      "esbuildConfigOverride": {
        "format": "esm",
        "target": "node16"
      },
      "packageFieldsToCopy": [
        "type"
      ],
      "zip": true,
      "packageFieldsToCopy": [
        "type"
      ],
    },
```
that should work fine, really sorry for the mistake.. Hope it works fine now.
Might be a good idea for the future to maybe add some warning and detect if some fields that are not supported have been entered into the config hah :D

**Comment by Twipped** [comment]
Aha, yep, that was the problem.

The call stack issue I'm having seems to be an issue in resolving circular dependencies. Specifically it's stuck in a loop trying  resolve ioredis code:

```lib/redis.js
../node_modules/ioredis/built/index.js
../node_modules/ioredis/built/Redis.js
../node_modules/@ioredis/commands/built/index.js
../node_modules/@ioredis/commands/built/commands.json
../node_modules/standard-as-callback/built/index.js
../node_modules/standard-as-callback/built/utils.js
../node_modules/ioredis/built/cluster/index.js
../node_modules/@ioredis/commands/built/index.js
../node_modules/@ioredis/commands/built/commands.json
../node_modules/redis-errors/index.js
../node_modules/redis-errors/lib/old.js
../node_modules/redis-errors/lib/modern.js
../node_modules/standard-as-callback/built/index.js
../node_modules/standard-as-callback/built/utils.js
../node_modules/ioredis/built/Command.js
../node_modules/@ioredis/commands/built/index.js
../node_modules/@ioredis/commands/built/commands.json
../node_modules/cluster-key-slot/lib/index.js
../node_modules/standard-as-callback/built/index.js
../node_modules/standard-as-callback/built/utils.js
../node_modules/ioredis/built/utils/index.js
../node_modules/ioredis/built/utils/lodash.js
../node_modules/lodash.defaults/index.js
../node_modules/lodash.isarguments/index.js
../node_modules/ioredis/built/utils/debug.js
../node_modules/debug/src/index.js
../node_modules/debug/src/browser.js
../node_modules/debug/src/common.js
../node_modules/debug/node_modules/ms/index.js
../node_modules/debug/src/node.js
../node_modules/supports-color/index.js
../node_modules/has-flag/index.js
../node_modules/debug/src/common.js
../node_modules/debug/node_modules/ms/index.js
../node_modules/ioredis/built/constants/TLSProfiles.js
../node_modules/ioredis/built/errors/ClusterAllFailedError.js
../node_modules/redis-errors/index.js
../node_modules/redis-errors/lib/old.js
../node_modules/redis-errors/lib/modern.js
../node_modules/ioredis/built/Redis.js
[ loops ]
```

**Comment by doteric** [comment]
Happy that the `funpack` issue was solved. Let me know if you have any other problems.

As for the `iosredis` problem, hard to say without a proper investigation, if you don't manage to find the issue you might want to create an issue on the `ioredis` github maybe? 🤔 

Btw. Let me know btw if I can close this issue.

**Comment by doteric** [comment]
Closing the issue, if you have any other questions or problems feel free to re-open or create another issue 😃

**Comment by Twipped** [comment]
@doteric the problem isn't with ioredis, the problem is that your dependency resolution doesn't account for circular dependencies. getImportedPackages has no checks for if its seen a dependency before. I'll try to make a demo project and open a new issue.

**Comment by doteric** [comment]
@Twipped Ohh, I understand you better now, I totally misunderstood you initially. So in case of an circular dependency there is a problem to finish the build right? Great catch, I will prepare a test for this tomorrow and solve this issue asap. Not sure if I'll have time to prepare the fix tomorrow, but definetly on Tuesday if not tomorrow. Thanks again 🙇 and sorry for misunderstanding :D

**Comment by doteric** [comment]
@Twipped 
PR to fix circular dependencies: https://github.com/doteric/funpack/pull/14  
You can test this with the following version: https://www.npmjs.com/package/funpack/v/1.3.0-beta-1

**Comment by Twipped** [comment]
@doteric Sorry for the delay, I've been too busy the last two weeks to get back to this.

1.3 is working great, the splitting is functional too. Is there a way to silence all the circular dependency alerts?
