### ISSUE TITLE
AWS lambda esm builds

### ISSUE THREAD

**Issue by emcfarlane** [doteric/funpack#18]
Thanks for the project! 🙏  The `"type": "module"` isn't passed down to package.json on built functions. AWS lambda thinks the module is a commonJS module and fails to parse.

Another option tried is editing the esbuild ext:
```
      "esbuildConfigOverride": {
        "format": "esm",
        "target": "node18",
        "outExtension": {
          ".js": ".mjs"
        }
      },
```

**Comment by emcfarlane** [comment]
Just saw this example: https://github.com/doteric/funpack/blob/master/examples/mjs-extension/package.json 👍

**Comment by doteric** [comment]
Hey @emcfarlane,
yes, exactly, you can override all the configuration options of esbuild using the funpack configuration. I would like to also add presets for specific setups, but no ETA's yet so you have to override the esbuild config.  
You can also use the `"type": "module"` from the package.json, here is an example: https://github.com/doteric/funpack/blob/master/examples/module-splitting/package.json#L12  
This configuration will also add the `type` inside the `package.json` of your output/bundle.

**Comment by emcfarlane** [comment]
Thanks!
